import {
    Briefcase,
    Monitor,
    PiggyBank,
    Coins,
    ShoppingCart,
    Home,
    Car,
    Gamepad2,
    Heart,
    GraduationCap,
    Shirt,
    MoreVertical,
    Zap,
    Coffee,
    Plane,
    Gift,
    Phone,
    Wifi,
    Utensils,
    Receipt,
    Music,
    Camera,
    Book,
    Dumbbell,
    Pill,
    Baby,
    Dog,
    Fuel,
    Bus,
    Train,
    CreditCard,
    Banknote,
    HandCoins,
    Landmark,
    Building,
    ShoppingBag,
    Pizza,
    Beer,
    Wine,
    Sparkles,
    Palette,
    Wrench,
    Hammer,
    Scissors,
    Glasses,
    Watch,
    Gem,
    Crown,
    Star,
    Wallet,
    TrendingUp,
    TrendingDown,
    DollarSign,
    Euro,
    Bitcoin,
    Percent,
    Calculator,
    FileText,
    FolderOpen,
    Archive,
    Package,
    Truck,
    MapPin,
    Navigation,
    Compass,
    Globe,
    Flag,
    Award,
    Trophy,
    Medal,
    Target,
    Crosshair,
    Lightbulb,
    Flame,
    Droplet,
    Snowflake,
    Sun,
    Moon,
    Cloud,
    Umbrella,
    Thermometer,
    Wind,
    Leaf,
    Flower2,
    Trees,
    Mountain,
    Waves,
    Anchor,
    Ship,
    Rocket,
    Satellite,
    Radio,
    Tv,
    Laptop,
    Smartphone,
    Tablet,
    Headphones,
    Speaker,
    Mic,
    Video,
    Film,
    Clapperboard,
    Popcorn,
    Ticket,
    PartyPopper,
    Cake,
    IceCream,
    Cookie,
    Apple,
    Banana,
    Cherry,
    Grape,
    Carrot,
    Salad,
    Sandwich,
    Soup,
    Fish,
    Beef,
    Egg,
    Milk,
    Croissant,
    Candy,
    Lollipop,
    CircleDollarSign,
    Wallet2,
    Receipt as ReceiptIcon,
    BadgeDollarSign,
    PoundSterling,
    RussianRuble,
    IndianRupee,
    JapaneseYen,
    SwissFranc,
    Banknote as BanknoteIcon,
    HandCoins as HandCoinsIcon,
    Landmark as LandmarkIcon,
    Building2,
    Factory,
    Store,
    ShoppingBasket,
    Barcode,
    QrCode,
    ScanLine,
    Printer,
    Keyboard,
    Mouse,
    HardDrive,
    Cpu,
    MemoryStick,
    Server,
    Database,
    Cloud as CloudIcon,
    Shield,
    Lock,
    Key,
    Fingerprint,
    Eye,
    EyeOff,
    Bell,
    BellRing,
    Mail,
    MessageSquare,
    MessageCircle,
    Send,
    Inbox,
    AtSign,
    Hash,
    Link,
    Paperclip,
    Bookmark,
    Tag,
    Tags,
    Folder,
    FolderPlus,
    FolderMinus,
    FolderOpen as FolderOpenIcon,
    File,
    FilePlus,
    FileEdit,
    FileCheck,
    Files,
    ClipboardList,
    ClipboardCheck,
    Calendar,
    CalendarDays,
    CalendarClock,
    Clock,
    Timer,
    Hourglass,
    AlarmClock,
    History,
    Repeat,
    RefreshCw,
    RotateCw,
    Download,
    Upload,
    Share,
    Share2,
    Copy,
    Clipboard,
    Crop,
    Move,
    ZoomIn,
    ZoomOut,
    Maximize,
    Minimize,
    ArrowUp,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ChevronUp,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronsUp,
    ChevronsDown,
    CornerDownRight,
    CornerUpLeft,
    Shuffle,
    Repeat1,
    Play,
    Pause,
    SkipBack,
    SkipForward,
    FastForward,
    Rewind,
    Volume,
    Volume1,
    Volume2,
    VolumeX,
    Smile,
    Frown,
    Meh,
    HeartHandshake,
    Handshake,
    Users,
    User,
    UserPlus,
    UserMinus,
    UserCheck,
    UserX,
    Users2,
    Contact,
    Contact2,
    PersonStanding,
    Accessibility,
    Activity,
    HeartPulse,
    Stethoscope,
    Syringe,
    Bandage,
    TestTube,
    Microscope,
    Brain,
    Bone,
    Footprints,
    Hand,
    Ear,
    LucideIcon,
} from "lucide-react";

export interface IconItem {
    id: string;
    icon: LucideIcon;
    name: string;
}

export const ICON_LIBRARY: IconItem[] = [
    // Dinheiro e Finanças
    { id: "wallet", icon: Wallet, name: "Carteira" },
    { id: "wallet2", icon: Wallet2, name: "Carteira 2" },
    { id: "coins", icon: Coins, name: "Moedas" },
    { id: "banknote", icon: Banknote, name: "Nota" },
    { id: "dollarsign", icon: DollarSign, name: "Dólar" },
    { id: "circledollar", icon: CircleDollarSign, name: "Círculo $" },
    { id: "badgedollar", icon: BadgeDollarSign, name: "Badge $" },
    { id: "euro", icon: Euro, name: "Euro" },
    { id: "pound", icon: PoundSterling, name: "Libra" },
    { id: "bitcoin", icon: Bitcoin, name: "Bitcoin" },
    { id: "yen", icon: JapaneseYen, name: "Yen" },
    { id: "rupee", icon: IndianRupee, name: "Rupia" },
    { id: "ruble", icon: RussianRuble, name: "Rublo" },
    { id: "franc", icon: SwissFranc, name: "Franco" },
    { id: "percent", icon: Percent, name: "Porcentagem" },
    { id: "calculator", icon: Calculator, name: "Calculadora" },
    { id: "creditcard", icon: CreditCard, name: "Cartão" },
    { id: "handcoins", icon: HandCoins, name: "Doação" },
    { id: "landmark", icon: Landmark, name: "Banco" },
    { id: "piggybank", icon: PiggyBank, name: "Cofrinho" },
    { id: "trendingup", icon: TrendingUp, name: "Alta" },
    { id: "trendingdown", icon: TrendingDown, name: "Baixa" },
    { id: "receipt", icon: Receipt, name: "Recibo" },

    // Trabalho
    { id: "briefcase", icon: Briefcase, name: "Trabalho" },
    { id: "building", icon: Building, name: "Prédio" },
    { id: "building2", icon: Building2, name: "Prédio 2" },
    { id: "factory", icon: Factory, name: "Fábrica" },
    { id: "store", icon: Store, name: "Loja" },

    // Compras
    { id: "shoppingcart", icon: ShoppingCart, name: "Carrinho" },
    { id: "shoppingbag", icon: ShoppingBag, name: "Sacola" },
    { id: "shoppingbasket", icon: ShoppingBasket, name: "Cesta" },
    { id: "barcode", icon: Barcode, name: "Código" },
    { id: "tag", icon: Tag, name: "Etiqueta" },
    { id: "tags", icon: Tags, name: "Etiquetas" },
    { id: "package", icon: Package, name: "Pacote" },

    // Casa
    { id: "home", icon: Home, name: "Casa" },
    { id: "lightbulb", icon: Lightbulb, name: "Luz" },
    { id: "droplet", icon: Droplet, name: "Água" },
    { id: "flame", icon: Flame, name: "Gás" },
    { id: "zap", icon: Zap, name: "Energia" },
    { id: "thermometer", icon: Thermometer, name: "Temperatura" },
    { id: "wind", icon: Wind, name: "Ar" },
    { id: "wrench", icon: Wrench, name: "Manutenção" },
    { id: "hammer", icon: Hammer, name: "Reforma" },

    // Transporte
    { id: "car", icon: Car, name: "Carro" },
    { id: "fuel", icon: Fuel, name: "Combustível" },
    { id: "bus", icon: Bus, name: "Ônibus" },
    { id: "train", icon: Train, name: "Trem" },
    { id: "plane", icon: Plane, name: "Avião" },
    { id: "ship", icon: Ship, name: "Navio" },
    { id: "rocket", icon: Rocket, name: "Foguete" },
    { id: "truck", icon: Truck, name: "Caminhão" },
    { id: "navigation", icon: Navigation, name: "GPS" },
    { id: "mappin", icon: MapPin, name: "Localização" },

    // Alimentação
    { id: "utensils", icon: Utensils, name: "Restaurante" },
    { id: "pizza", icon: Pizza, name: "Pizza" },
    { id: "coffee", icon: Coffee, name: "Café" },
    { id: "beer", icon: Beer, name: "Bar" },
    { id: "wine", icon: Wine, name: "Vinho" },
    { id: "sandwich", icon: Sandwich, name: "Sanduíche" },
    { id: "soup", icon: Soup, name: "Sopa" },
    { id: "salad", icon: Salad, name: "Salada" },
    { id: "apple", icon: Apple, name: "Frutas" },
    { id: "carrot", icon: Carrot, name: "Vegetais" },
    { id: "fish", icon: Fish, name: "Peixe" },
    { id: "beef", icon: Beef, name: "Carne" },
    { id: "egg", icon: Egg, name: "Ovos" },
    { id: "milk", icon: Milk, name: "Leite" },
    { id: "croissant", icon: Croissant, name: "Padaria" },
    { id: "cake", icon: Cake, name: "Bolo" },
    { id: "icecream", icon: IceCream, name: "Sorvete" },
    { id: "candy", icon: Candy, name: "Doces" },
    { id: "popcorn", icon: Popcorn, name: "Pipoca" },

    // Saúde
    { id: "heart", icon: Heart, name: "Saúde" },
    { id: "heartpulse", icon: HeartPulse, name: "Batimentos" },
    { id: "stethoscope", icon: Stethoscope, name: "Médico" },
    { id: "syringe", icon: Syringe, name: "Vacina" },
    { id: "pill", icon: Pill, name: "Remédio" },
    { id: "bandage", icon: Bandage, name: "Curativo" },
    { id: "testtube", icon: TestTube, name: "Exame" },
    { id: "microscope", icon: Microscope, name: "Laboratório" },
    { id: "brain", icon: Brain, name: "Mente" },
    { id: "dumbbell", icon: Dumbbell, name: "Academia" },
    { id: "activity", icon: Activity, name: "Atividade" },

    // Educação
    { id: "graduation", icon: GraduationCap, name: "Formatura" },
    { id: "book", icon: Book, name: "Livro" },
    { id: "notebook", icon: FileText, name: "Caderno" },

    // Tecnologia
    { id: "monitor", icon: Monitor, name: "Monitor" },
    { id: "laptop", icon: Laptop, name: "Notebook" },
    { id: "smartphone", icon: Smartphone, name: "Celular" },
    { id: "tablet", icon: Tablet, name: "Tablet" },
    { id: "headphones", icon: Headphones, name: "Fone" },
    { id: "speaker", icon: Speaker, name: "Caixa" },
    { id: "tv", icon: Tv, name: "TV" },
    { id: "gamepad", icon: Gamepad2, name: "Jogos" },
    { id: "camera", icon: Camera, name: "Câmera" },
    { id: "radio", icon: Radio, name: "Rádio" },
    { id: "wifi", icon: Wifi, name: "Internet" },
    { id: "phone", icon: Phone, name: "Telefone" },
    { id: "printer", icon: Printer, name: "Impressora" },
    { id: "keyboard", icon: Keyboard, name: "Teclado" },
    { id: "mouse", icon: Mouse, name: "Mouse" },
    { id: "harddrive", icon: HardDrive, name: "HD" },
    { id: "cpu", icon: Cpu, name: "Processador" },
    { id: "server", icon: Server, name: "Servidor" },
    { id: "database", icon: Database, name: "Banco" },
    { id: "cloud", icon: Cloud, name: "Nuvem" },

    // Entretenimento
    { id: "music", icon: Music, name: "Música" },
    { id: "film", icon: Film, name: "Filme" },
    { id: "video", icon: Video, name: "Vídeo" },
    { id: "ticket", icon: Ticket, name: "Ingresso" },
    { id: "party", icon: PartyPopper, name: "Festa" },

    // Vestuário e Beleza
    { id: "shirt", icon: Shirt, name: "Roupa" },
    { id: "sparkles", icon: Sparkles, name: "Beleza" },
    { id: "scissors", icon: Scissors, name: "Cabelo" },
    { id: "glasses", icon: Glasses, name: "Óculos" },
    { id: "watch", icon: Watch, name: "Relógio" },
    { id: "gem", icon: Gem, name: "Jóias" },
    { id: "crown", icon: Crown, name: "Premium" },
    { id: "palette", icon: Palette, name: "Arte" },

    // Família e Pets
    { id: "baby", icon: Baby, name: "Bebê" },
    { id: "users", icon: Users, name: "Família" },
    { id: "user", icon: User, name: "Pessoa" },
    { id: "dog", icon: Dog, name: "Pet" },
    { id: "handshake", icon: Handshake, name: "Acordo" },

    // Natureza
    { id: "leaf", icon: Leaf, name: "Folha" },
    { id: "flower", icon: Flower2, name: "Flor" },
    { id: "trees", icon: Trees, name: "Árvores" },
    { id: "mountain", icon: Mountain, name: "Montanha" },
    { id: "waves", icon: Waves, name: "Ondas" },
    { id: "sun", icon: Sun, name: "Sol" },
    { id: "moon", icon: Moon, name: "Lua" },
    { id: "umbrella", icon: Umbrella, name: "Guarda-chuva" },
    { id: "snowflake", icon: Snowflake, name: "Neve" },
    { id: "globe", icon: Globe, name: "Mundo" },

    // Conquistas
    { id: "star", icon: Star, name: "Estrela" },
    { id: "award", icon: Award, name: "Prêmio" },
    { id: "trophy", icon: Trophy, name: "Troféu" },
    { id: "medal", icon: Medal, name: "Medalha" },
    { id: "target", icon: Target, name: "Meta" },
    { id: "flag", icon: Flag, name: "Bandeira" },

    // Segurança
    { id: "shield", icon: Shield, name: "Escudo" },
    { id: "lock", icon: Lock, name: "Cadeado" },
    { id: "key", icon: Key, name: "Chave" },

    // Comunicação
    { id: "mail", icon: Mail, name: "Email" },
    { id: "message", icon: MessageSquare, name: "Mensagem" },
    { id: "bell", icon: Bell, name: "Notificação" },
    { id: "send", icon: Send, name: "Enviar" },

    // Organização  
    { id: "calendar", icon: Calendar, name: "Calendário" },
    { id: "clock", icon: Clock, name: "Relógio" },
    { id: "timer", icon: Timer, name: "Timer" },
    { id: "folder", icon: Folder, name: "Pasta" },
    { id: "file", icon: File, name: "Arquivo" },
    { id: "clipboard", icon: ClipboardList, name: "Lista" },
    { id: "bookmark", icon: Bookmark, name: "Favorito" },
    { id: "archive", icon: Archive, name: "Arquivo" },

    // Presente e Doação
    { id: "gift", icon: Gift, name: "Presente" },
    { id: "hearthand", icon: HeartHandshake, name: "Caridade" },

    // Outros
    { id: "other", icon: MoreVertical, name: "Outros" },
];

export const getIconById = (iconId: string): LucideIcon => {
    const item = ICON_LIBRARY.find(i => i.id === iconId);
    return item?.icon || MoreVertical;
};

export const getIconName = (iconId: string): string => {
    const item = ICON_LIBRARY.find(i => i.id === iconId);
    return item?.name || "Outros";
};
