"use client";

import { useMemo } from "react";
import { useTransactions } from "@/hooks/useTransactions";
import { useAccounts } from "@/hooks/useAccounts";
import { useRecurring } from "@/hooks/useRecurring";
import { useGoals } from "@/hooks/useGoals";
import { isSameMonth, subMonths, getDaysInMonth, differenceInCalendarMonths } from "date-fns";
import { Transaction } from "@/types";

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

function getMonthlyIncome(transactions: Transaction[], targetDate: Date): number {
    return transactions
        .filter(
            (t) =>
                isSameMonth(t.date, targetDate) &&
                t.type === "receita" &&
                t.category !== "Transferência"
        )
        .reduce((s, t) => s + t.amount, 0);
}

/**
 * Variable spending = despesas that are NOT linked to a recurring rule.
 * Expenses generated by recurring rules are already accounted for in
 * `fixedExpenses`, so we exclude them to avoid double-counting.
 */
function getVariableSpending(transactions: Transaction[], targetDate: Date): number {
    return transactions
        .filter(
            (t) =>
                isSameMonth(t.date, targetDate) &&
                t.type === "despesa" &&
                t.category !== "Transferência" &&
                !t.recurringTransactionId
        )
        .reduce((s, t) => s + t.amount, 0);
}

function r2(v: number) {
    return Math.round(v * 100) / 100;
}

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

export type SafeToSpendWarning =
    | "commitments_exceed_income" // fixed + goals + buffer >= income
    | "overspent"                 // already exceeded this month's variable budget
    | "low_balance"               // liquid balance < 1 month variable budget
    | undefined;

export interface SafeToSpendData {
    /** false while loading or while user doesn't have 1 completed month yet */
    available: boolean;
    loading: boolean;

    /** R$ safe to spend TODAY (includes accumulated days not spent) */
    safeAmount: number;

    /** R$ allocated per calendar day */
    dailyBudget: number;

    /** R$ total variable budget for the whole month */
    monthlyDisposable: number;

    /** Extra full days of allowance banked (beyond today's daily allocation) */
    accumulatedDays: number;

    /** R$ already spent on variable expenses this month */
    variableSpentThisMonth: number;

    /** 0–100 — how much of the monthly variable budget has been used */
    monthlyBudgetUsedPct: number;

    warning: SafeToSpendWarning;

    /** Breakdown for transparency ("why is my budget R$X?") */
    breakdown: {
        avgIncome: number;         // conservative income baseline (90% of avg)
        fixedExpenses: number;     // monthly recurring fixed expenses
        goalContributions: number; // total monthly contribution needed for goals
        safetyBuffer: number;      // 10% of income, never shown as spendable
    };
}

const NOT_AVAILABLE: SafeToSpendData = {
    available: false,
    loading: false,
    safeAmount: 0,
    dailyBudget: 0,
    monthlyDisposable: 0,
    accumulatedDays: 0,
    variableSpentThisMonth: 0,
    monthlyBudgetUsedPct: 0,
    warning: undefined,
    breakdown: { avgIncome: 0, fixedExpenses: 0, goalContributions: 0, safetyBuffer: 0 },
};

// ─────────────────────────────────────────────────────────────────────────────
// Hook
// ─────────────────────────────────────────────────────────────────────────────

export function useSafeToSpend(): SafeToSpendData {
    const { transactions, loading: loadingTx } = useTransactions();
    const { accounts, loading: loadingAccounts } = useAccounts();
    const { recurring, loading: loadingRecurring } = useRecurring();
    const { goals, loading: loadingGoals } = useGoals();

    const loading = loadingTx || loadingAccounts || loadingRecurring || loadingGoals;

    return useMemo<SafeToSpendData>(() => {
        if (loading) return { ...NOT_AVAILABLE, loading: true };

        const now = new Date();

        // ─────────────────────────────────────────────────────────────
        // STEP 1 — History check
        // Require at least 1 completed month with income.
        // This prevents misleading results for brand-new users.
        // ─────────────────────────────────────────────────────────────
        const incomeLastMonth = getMonthlyIncome(transactions, subMonths(now, 1));
        const income2MonthsAgo = getMonthlyIncome(transactions, subMonths(now, 2));
        const hasHistory = incomeLastMonth > 0 || income2MonthsAgo > 0;

        if (!hasHistory) return NOT_AVAILABLE;

        // ─────────────────────────────────────────────────────────────
        // STEP 2 — Conservative income baseline
        // Use only COMPLETED months (never the current partial month).
        // Apply 90% factor to protect against variability: if one month
        // had an exceptional bonus, the daily budget should not spike.
        // ─────────────────────────────────────────────────────────────
        const completedIncomes = [incomeLastMonth, income2MonthsAgo].filter((v) => v > 0);
        const avgIncome = completedIncomes.reduce((s, v) => s + v, 0) / completedIncomes.length;
        const conservativeIncome = avgIncome * 0.9;

        // ─────────────────────────────────────────────────────────────
        // STEP 3 — Monthly fixed commitments (recurring rules)
        // Only active expense rules. Recurring income is already
        // captured in the income baseline above.
        // ─────────────────────────────────────────────────────────────
        const fixedExpenses = recurring
            .filter((r) => r.active && r.type === "despesa")
            .reduce((s, r) => s + r.amount, 0);

        // ─────────────────────────────────────────────────────────────
        // STEP 4 — Goal monthly contributions
        // For each active goal with a future deadline, calculate how
        // much needs to be saved per month to reach it on time.
        // Goals without deadlines are excluded (not time-bound pressure).
        // ─────────────────────────────────────────────────────────────
        const goalContributions = goals
            .filter((g) => g.status !== "concluida" && g.deadline)
            .reduce((s, g) => {
                const remaining = (g.targetAmount || 0) - (g.currentAmount || 0);
                if (remaining <= 0) return s;

                const deadline = g.deadline instanceof Date ? g.deadline : new Date(g.deadline);
                // monthsLeft: at least 1 to avoid dividing by zero on same-month deadlines
                const monthsLeft = Math.max(1, differenceInCalendarMonths(deadline, now));
                return s + remaining / monthsLeft;
            }, 0);

        // ─────────────────────────────────────────────────────────────
        // STEP 5 — Safety buffer
        // 10% of income, minimum R$200.
        // This money is never shown as available to spend — it's the
        // cushion that protects against unexpected expenses.
        // ─────────────────────────────────────────────────────────────
        const safetyBuffer = Math.max(200, conservativeIncome * 0.1);

        const breakdown = {
            avgIncome: r2(conservativeIncome),
            fixedExpenses: r2(fixedExpenses),
            goalContributions: r2(goalContributions),
            safetyBuffer: r2(safetyBuffer),
        };

        // ─────────────────────────────────────────────────────────────
        // STEP 6 — Monthly disposable budget
        // What remains after all commitments and the safety buffer.
        // ─────────────────────────────────────────────────────────────
        const monthlyDisposable = Math.max(
            0,
            conservativeIncome - fixedExpenses - goalContributions - safetyBuffer
        );

        const variableSpentThisMonth = r2(getVariableSpending(transactions, now));

        if (monthlyDisposable === 0) {
            return {
                available: true,
                loading: false,
                safeAmount: 0,
                dailyBudget: 0,
                monthlyDisposable: 0,
                accumulatedDays: 0,
                variableSpentThisMonth,
                monthlyBudgetUsedPct: 100,
                warning: "commitments_exceed_income",
                breakdown,
            };
        }

        // ─────────────────────────────────────────────────────────────
        // STEP 7 — Daily budget and natural accumulation
        //
        // dailyBudget = monthlyDisposable / days_in_month
        // accruedBudget = dailyBudget × day_of_month
        //
        // Example: daily = R$50, today is day 10 → accrued = R$500.
        // If only R$300 was spent in variable expenses → safe = R$200.
        // (This R$200 already includes today's R$50 + 3 banked days × R$50)
        //
        // Accumulation is implicit in the math — no separate tracking needed.
        // ─────────────────────────────────────────────────────────────
        const daysInMonth = getDaysInMonth(now);
        const dailyBudget = monthlyDisposable / daysInMonth;
        const dayOfMonth = now.getDate();
        const accruedBudget = dailyBudget * dayOfMonth;
        const rawSafe = accruedBudget - variableSpentThisMonth;

        // ─────────────────────────────────────────────────────────────
        // STEP 8 — Balance safety check
        // The algorithm works on averages and rules — but if the actual
        // liquid balance is below the monthly variable budget, something
        // is off (unregistered expenses, overdue bills, etc.).
        // In that case, halve the recommendation to protect the user.
        // ─────────────────────────────────────────────────────────────
        const liquidBalance = accounts
            .filter((a) => a.type !== "investment")
            .reduce((s, a) => s + Math.max(0, a.balance), 0);

        let safeAmount = Math.max(0, rawSafe);
        let warning: SafeToSpendWarning = undefined;

        if (rawSafe < 0) {
            warning = "overspent";
        } else if (liquidBalance < monthlyDisposable) {
            safeAmount = safeAmount * 0.5;
            warning = "low_balance";
        }

        // Extra full days banked beyond today's allocation
        const accumulatedDays =
            safeAmount > dailyBudget
                ? Math.floor((safeAmount - dailyBudget) / dailyBudget)
                : 0;

        const monthlyBudgetUsedPct = Math.min(
            100,
            Math.round((variableSpentThisMonth / monthlyDisposable) * 100)
        );

        return {
            available: true,
            loading: false,
            safeAmount: r2(safeAmount),
            dailyBudget: r2(dailyBudget),
            monthlyDisposable: r2(monthlyDisposable),
            accumulatedDays,
            variableSpentThisMonth,
            monthlyBudgetUsedPct,
            warning,
            breakdown,
        };
    }, [transactions, accounts, recurring, goals, loading]);
}
